services:
  pihole:
    container_name: pihole
    hostname: "ns"
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
    volumes:
      - '/srv/volumes/pihole/etc-pihole:/etc/pihole'
    restart: unless-stopped
