services:
  portainer-agent:
    container_name: 'portainer-agent'
    image: portainer/agent:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
