services:
  watchtower:
    container_name: "watchtower"
    hostname: "watchtower"
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      WATCHTOWER_NOTIFICATION_URL: ${DISCORD_NOTIFY_URL}
